services:
  ml:
    build: ./ml_model
    container_name: traffic-ai-ml
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  app:
    build: .
    container_name: traffic-ai-app
    ports:
      - "4000:4000"
    depends_on:
      - ml
    environment:
      - LOCAL_ML_API_URL=http://ml:8000
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./ml_model:/app/ml_model
    stdin_open: true
    tty: true
